create or replace FUNCTION checkIsPurseNew(
  CURRENCY_TYPE IN PARAMETERS.VALUE%TYPE,
  USER_ID IN OBJECTS.PARENTID%TYPE
)
  RETURN OBJECTS.OBJECTID%TYPE
IS
  VAR_PURSE_OBJECT_ID OBJECTS.OBJECTID%TYPE;
    EXCEPTION_USER_IS_NOT_EXIST EXCEPTION;
  BEGIN
    Select OBJECTS.OBJECTID INTO VAR_PURSE_OBJECT_ID
    FROM OBJECTS, OBJREFERENCE, PARAMETERS
    WHERE OBJECTS.PARENTID = USER_ID
          AND OBJECTS.OBJECTID = OBJREFERENCE.REFERENCE
          AND OBJREFERENCE.OBJECTID = PARAMETERS.OBJECTID
          AND OBJREFERENCE.ATTRID = 13
          AND PARAMETERS.VALUE = CURRENCY_TYPE;
    RETURN VAR_PURSE_OBJECT_ID;
    EXCEPTION WHEN NO_DATA_FOUND THEN
    BEGIN
      RETURN -1;
    END;
  END;
/